//
// Floppy layout generated by FloppyBuilder 0.19
//

#ifdef ASSEMBLER
//
// Information for the Assembler
//
#ifdef LOADER
FileStartSector .byt 4,8,11,10,11,11,1,8,15,5,12,2,9,16,6,13,3,10,17,7,14,4,11,1,8,15,5,12,2,9,16,6,13,3,10,17,7,14,4,11,1,8,15,5,12,2,9,16,6,13,3,10,17,7,14,4
FileStartTrack .byt 0,0,4,6,13,21,22,22,22,23,23,24,24,24,25,25,26,26,26,27,27,28,28,29,29,29,30,30,31,31,31,32,32,33,33,33,34,34,35,35,36,36,36,37,37,38,38,38,39,39,40,40,40,41,41,128
FileStoredSizeLow .byt <1024,<18176,<8448,<30720,<34816,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<8704
FileStoredSizeHigh .byt >1024,>18176,>8448,>30720,>34816,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>8704
FileSizeLow .byt <1024,<18176,<8448,<30720,<34816,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<1792,<8704
FileSizeHigh .byt >1024,>18176,>8448,>30720,>34816,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>1792,>8704
FileLoadAdressLow .byt <64512,<4096,<2048,<2048,<2048,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2560,<2048
FileLoadAdressHigh .byt >64512,>4096,>2048,>2048,>2048,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2560,>2048
#endif // LOADER
#else
//
// Information for the Compiler
//
#endif

//
// Summary for this floppy building session:
//
#define FLOPPY_SIDE_NUMBER 2    // Number of sides
#define FLOPPY_TRACK_NUMBER 42    // Number of tracks
#define FLOPPY_SECTOR_PER_TRACK 17   // Number of sectors per track

//
// List of files written to the floppy
//
// Entry #0 '..\build\files\loader.o'
// - Loads at address 64512 starts on track 0 sector 4 and is 4 sectors long (1024 bytes).
// Entry #1 '..\Extraction\introBars.bin'
// - Loads at address 4096 starts on track 0 sector 8 and is 71 sectors long (18176 bytes).
// Entry #2 '..\Extraction\displayExocetMoon.bin'
// - Loads at address 2048 starts on track 4 sector 11 and is 33 sectors long (8448 bytes).
// Entry #3 '..\Extraction\rotozoom.bin'
// - Loads at address 2048 starts on track 6 sector 10 and is 120 sectors long (30720 bytes).
// Entry #4 '..\Extraction\concentricCircles.bin'
// - Loads at address 2048 starts on track 13 sector 11 and is 136 sectors long (34816 bytes).
// Entry #5 '..\Extraction\File_10.bin'
// - Loads at address 2560 starts on track 21 sector 11 and is 7 sectors long (1792 bytes).
// Entry #6 '..\Extraction\File_11.bin'
// - Loads at address 2560 starts on track 22 sector 1 and is 7 sectors long (1792 bytes).
// Entry #7 '..\Extraction\File_12.bin'
// - Loads at address 2560 starts on track 22 sector 8 and is 7 sectors long (1792 bytes).
// Entry #8 '..\Extraction\File_13.bin'
// - Loads at address 2560 starts on track 22 sector 15 and is 7 sectors long (1792 bytes).
// Entry #9 '..\Extraction\File_14.bin'
// - Loads at address 2560 starts on track 23 sector 5 and is 7 sectors long (1792 bytes).
// Entry #10 '..\Extraction\File_15.bin'
// - Loads at address 2560 starts on track 23 sector 12 and is 7 sectors long (1792 bytes).
// Entry #11 '..\Extraction\File_16.bin'
// - Loads at address 2560 starts on track 24 sector 2 and is 7 sectors long (1792 bytes).
// Entry #12 '..\Extraction\File_17.bin'
// - Loads at address 2560 starts on track 24 sector 9 and is 7 sectors long (1792 bytes).
// Entry #13 '..\Extraction\File_18.bin'
// - Loads at address 2560 starts on track 24 sector 16 and is 7 sectors long (1792 bytes).
// Entry #14 '..\Extraction\File_19.bin'
// - Loads at address 2560 starts on track 25 sector 6 and is 7 sectors long (1792 bytes).
// Entry #15 '..\Extraction\File_20.bin'
// - Loads at address 2560 starts on track 25 sector 13 and is 7 sectors long (1792 bytes).
// Entry #16 '..\Extraction\File_21.bin'
// - Loads at address 2560 starts on track 26 sector 3 and is 7 sectors long (1792 bytes).
// Entry #17 '..\Extraction\File_22.bin'
// - Loads at address 2560 starts on track 26 sector 10 and is 7 sectors long (1792 bytes).
// Entry #18 '..\Extraction\File_23.bin'
// - Loads at address 2560 starts on track 26 sector 17 and is 7 sectors long (1792 bytes).
// Entry #19 '..\Extraction\File_24.bin'
// - Loads at address 2560 starts on track 27 sector 7 and is 7 sectors long (1792 bytes).
// Entry #20 '..\Extraction\File_25.bin'
// - Loads at address 2560 starts on track 27 sector 14 and is 7 sectors long (1792 bytes).
// Entry #21 '..\Extraction\File_26.bin'
// - Loads at address 2560 starts on track 28 sector 4 and is 7 sectors long (1792 bytes).
// Entry #22 '..\Extraction\File_27.bin'
// - Loads at address 2560 starts on track 28 sector 11 and is 7 sectors long (1792 bytes).
// Entry #23 '..\Extraction\File_28.bin'
// - Loads at address 2560 starts on track 29 sector 1 and is 7 sectors long (1792 bytes).
// Entry #24 '..\Extraction\File_29.bin'
// - Loads at address 2560 starts on track 29 sector 8 and is 7 sectors long (1792 bytes).
// Entry #25 '..\Extraction\File_30.bin'
// - Loads at address 2560 starts on track 29 sector 15 and is 7 sectors long (1792 bytes).
// Entry #26 '..\Extraction\File_31.bin'
// - Loads at address 2560 starts on track 30 sector 5 and is 7 sectors long (1792 bytes).
// Entry #27 '..\Extraction\File_32.bin'
// - Loads at address 2560 starts on track 30 sector 12 and is 7 sectors long (1792 bytes).
// Entry #28 '..\Extraction\File_33.bin'
// - Loads at address 2560 starts on track 31 sector 2 and is 7 sectors long (1792 bytes).
// Entry #29 '..\Extraction\File_34.bin'
// - Loads at address 2560 starts on track 31 sector 9 and is 7 sectors long (1792 bytes).
// Entry #30 '..\Extraction\File_35.bin'
// - Loads at address 2560 starts on track 31 sector 16 and is 7 sectors long (1792 bytes).
// Entry #31 '..\Extraction\File_36.bin'
// - Loads at address 2560 starts on track 32 sector 6 and is 7 sectors long (1792 bytes).
// Entry #32 '..\Extraction\File_37.bin'
// - Loads at address 2560 starts on track 32 sector 13 and is 7 sectors long (1792 bytes).
// Entry #33 '..\Extraction\File_38.bin'
// - Loads at address 2560 starts on track 33 sector 3 and is 7 sectors long (1792 bytes).
// Entry #34 '..\Extraction\File_39.bin'
// - Loads at address 2560 starts on track 33 sector 10 and is 7 sectors long (1792 bytes).
// Entry #35 '..\Extraction\File_40.bin'
// - Loads at address 2560 starts on track 33 sector 17 and is 7 sectors long (1792 bytes).
// Entry #36 '..\Extraction\File_41.bin'
// - Loads at address 2560 starts on track 34 sector 7 and is 7 sectors long (1792 bytes).
// Entry #37 '..\Extraction\File_42.bin'
// - Loads at address 2560 starts on track 34 sector 14 and is 7 sectors long (1792 bytes).
// Entry #38 '..\Extraction\File_43.bin'
// - Loads at address 2560 starts on track 35 sector 4 and is 7 sectors long (1792 bytes).
// Entry #39 '..\Extraction\File_44.bin'
// - Loads at address 2560 starts on track 35 sector 11 and is 7 sectors long (1792 bytes).
// Entry #40 '..\Extraction\File_45.bin'
// - Loads at address 2560 starts on track 36 sector 1 and is 7 sectors long (1792 bytes).
// Entry #41 '..\Extraction\File_46.bin'
// - Loads at address 2560 starts on track 36 sector 8 and is 7 sectors long (1792 bytes).
// Entry #42 '..\Extraction\File_47.bin'
// - Loads at address 2560 starts on track 36 sector 15 and is 7 sectors long (1792 bytes).
// Entry #43 '..\Extraction\File_48.bin'
// - Loads at address 2560 starts on track 37 sector 5 and is 7 sectors long (1792 bytes).
// Entry #44 '..\Extraction\File_49.bin'
// - Loads at address 2560 starts on track 37 sector 12 and is 7 sectors long (1792 bytes).
// Entry #45 '..\Extraction\File_50.bin'
// - Loads at address 2560 starts on track 38 sector 2 and is 7 sectors long (1792 bytes).
// Entry #46 '..\Extraction\File_51.bin'
// - Loads at address 2560 starts on track 38 sector 9 and is 7 sectors long (1792 bytes).
// Entry #47 '..\Extraction\File_52.bin'
// - Loads at address 2560 starts on track 38 sector 16 and is 7 sectors long (1792 bytes).
// Entry #48 '..\Extraction\File_53.bin'
// - Loads at address 2560 starts on track 39 sector 6 and is 7 sectors long (1792 bytes).
// Entry #49 '..\Extraction\File_54.bin'
// - Loads at address 2560 starts on track 39 sector 13 and is 7 sectors long (1792 bytes).
// Entry #50 '..\Extraction\File_55.bin'
// - Loads at address 2560 starts on track 40 sector 3 and is 7 sectors long (1792 bytes).
// Entry #51 '..\Extraction\File_56.bin'
// - Loads at address 2560 starts on track 40 sector 10 and is 7 sectors long (1792 bytes).
// Entry #52 '..\Extraction\File_57.bin'
// - Loads at address 2560 starts on track 40 sector 17 and is 7 sectors long (1792 bytes).
// Entry #53 '..\Extraction\File_58.bin'
// - Loads at address 2560 starts on track 41 sector 7 and is 7 sectors long (1792 bytes).
// Entry #54 '..\Extraction\File_59.bin'
// - Loads at address 2560 starts on track 41 sector 14 and is 7 sectors long (1792 bytes).
// Entry #55 '..\Extraction\scrollChessboard.bin'
// - Loads at address 2048 starts on the second side on track 0 sector 4 and is 34 sectors long (8704 bytes).
//
// 751 sectors used, out of 1428. (52% of the total disk size used)
//
#define LOADER_FIRST_PART 1

//
// Metadata
//
#ifdef METADATA_STORAGE

#endif // METADATA_STORAGE

